version: '3.3'

services:
  webserver:
    container_name: migaga
    image: migaga
    volumes:
      - ./:/usr/src/app
      - webrootuservolume:/root
  database:
    container_name: database
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - datavolume:/var/lib/mysql
    ports:
      - '3306:3306'
    command: mysqld --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
volumes:
  datavolume:
  webrootuservolume:
