version: '3.4'

services:
  migaga:
    image: migaga
    volumes:
      - ./:/usr/src/app
      - webrootuservolume:/root
    build:
      context: .
      dockerfile: Dockerfile
  database:
    container_name: database
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - datavolume:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  datavolume:
  webrootuservolume: