version: '3.4'

services:
  migaga:
    image: migaga
    container_name: migaga
    networks:
      - dbnetwork
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile

  migaga_database:
    container_name: migaga-database
    image: mysql/mysql-server
    networks:
      - dbnetwork
    environment:
      MYSQL_ROOT_PASSWORD: mg-password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - databasevolume:/var/lib/mysql
    ports:
      - '3307:3307'

  adminer:
    image: adminer
    networks:
      - dbnetwork
    ports:
      - '8080:8080'

volumes:
  databasevolume:

networks:
  dbnetwork: